{% set name = "sbml2sbol" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neilswainston/SbmlToSbol/archive/{{ version }}.tar.gz
  sha256: 21022797453452c6f5fcd7d4fc5d4691291dd0cbe7349a8565d39f424f9928ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - python-libsbml
    - pysbol2
    - synbiochem-py

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - pytest -v tests

about:
  home: https://github.com/neilswainston/SbmlToSbol
  summary: Convert sbml to sbol format
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - breakthewall
